language: go

env:
  - VERSION="0.$TRAVIS_BUILD_NUMBER"

go:
  - 1.16.x

git:
  depth: false
  quiet: true
  submodules: false

branches:
  only:
    - master

services:
  - docker

script:
  - "make test"
  - "VERSION=$VERSION make image"
  - curl -sfL https://git.io/goreleaser | sh -s -- check

before_deploy:
  - git config --local user.name "pete911"
  - git config --local user.email "p.reisinger@gmail.com"
  - git tag $VERSION

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

after_success:
  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
  VERSION=$VERSION make push-image ;
