language: go

env:
  - VERSION="0.$TRAVIS_BUILD_NUMBER"

go:
  - 1.16.x

git:
  depth: false
  quiet: true
  submodules: false

branches:
  only:
    - master

services:
  - docker

script:
  - "make test"
  - "VERSION=$VERSION make image"
  - "make release"

before_deploy:
  - git config --local user.name "pete911"
  - git config --local user.email "p.reisinger@gmail.com"
  - git tag $VERSION

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "releases/certinfo_darwin_amd64.tar.gz"
    - "releases/certinfo_darwin_arm64.tar.gz"
    - "releases/certinfo_linux_amd64.tar.gz"
    - "releases/certinfo_windows_amd64.tar.gz"
  skip_cleanup: true

after_success:
  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
  VERSION=$VERSION make push-image ;
